### ISSUE TITLE
愛醬沒有回應

### ISSUE THREAD

**Issue by Domoku0609** [mao-shonen/LINE-chat-bot#13]
不好意思打擾了，先這邊感謝作者大大編寫愛醬給我帶來的樂趣和方便。
回到主題，今天呼叫愛醬或打關鍵字都沒有反應，是不是愛醬又壞掉了呢？
如果是的話，請問作者大大還會再弄一個新的嗎？>_<

**Comment by maou-shonen** [comment]
伺服器是放在我自己家裡的
偶爾會因為一些攻擊或是系統操作短暫中斷
沒有特別通知的話
即使掛掉也會重新製作
反正LINE也沒告知我任何訊息
